### PR TITLE
Fix tests

### LINKED ISSUE #23: Facebook Facepile not rendering
`ember serve` the dummy app. Facepile doesn't show:
* without parameters - nothing shows
* custom URL - facebook icon and likes shown. No faces.
* with theme - only a black bar shows for 'dark' theme.

### LINKED ISSUE #31: Count Display API is not consistent between components
The count display for twitter shares is:

`{{twitter-share count='horizontal'}}`

With `vertical` as the other option, displaying the count on the _right_ and _top_, respectively.

However, for linkedin shares, the API is:

`{{linkedin-share count='top'}}`

With `right` as the other option.

It would make more sense for the Twitter-Share component to align with the Linkedin-Share API.

### LINKED ISSUE #45: Deprecation warnings on Ember 2.7.0
Some deprecation warnings are thrown in regards to services when using the addon with Ember 2.7.0.

screen shot 2016-09-09 at 12 02 33

### PR DESCRIPTION
**Pull request by locks**
Fixes #23. Fixes #31. Fixes #36. Fixes #45.

I believe this will require a major version bump, as the `facepile` component had to be removed due to the API being deprecated by Facebook. You can see more detail in the related commit message.
Twitter's share component also got the counts removed.

### CODE REVIEW

**Comment by ksin** [comment]
Thanks @locks ! Just tagging this issue here:
https://github.com/plyfe/ember-social/issues/23

**Comment by ksin** [comment]
Can you also remove the `facepile` docs in the README?

**Comment by locks** [comment]
Will do! We still have some failing tests, I believe due to CSP, investigating.

**Comment by anvyst** [comment]
My attempt trying to debug the issue with failed tests ended up with the following results.

The problems start with:

```javascript
Ember.$.getScript("//platform.linkedin.com/in.js?async=true", function success() {
       IN.shareHandlerName = shareHandlerName;
       IN.Event.on(IN, 'systemReady', Ember.run.bind(null, resolve, IN));
       IN.init();
});
```


It loads couple of nasty JS files and one of them (`secureAnonymousFramework`) breaks the tests:
```
not ok 14 PhantomJS 1.9 - Global error: Script error. at , line 0
    ---
        Log: |
            { type: 'error', text: 'Script error. at , line 0\n' }
``` 

In the browser It'd look like: 
`Uncaught TypeError: Cannot read property 'Function' of undefined secureAnonymousFramework?v=0.0.2000-RC8.57838-1429&:1033`

Going deeper in the code, it breaks on `Sslac.Function(...)`

At the same time, if you load dummy/app `/linkedin/share` page, the above script loads properly and hooks `Sslac` to `window` object. 
Unfortunately, I couldn't find the reason it doesn't hook to `window` when it's run via `ember test -s`.

**Comment by locks** [comment]
As @anvyst mentions, the manual tests seem to work but not the automated ones. Thoughts on how to proceed? :X

**Pull request merged**
