### PR TITLE
Exposes related, via, and hashtags attrs for twitter share link.

### PR DESCRIPTION
**Pull request by patrickberkeley**
Twitter docs: https://dev.twitter.com/web/tweet-button/web-intent

### CODE REVIEW

**Comment by lukemelia** [comment]
Thanks. Can you add tests and some examples to `tests/dummy/app/templates/twitter/share.hbs`?

**Comment by patrickberkeley** [comment]
Sure thing! Added here: d888dce665905b6f4ccf3c62f3c96a66c0479625. Let me know if you'd like more coverage.

**Comment by lukemelia** [comment]
@patrickberkeley looks like these are failing on Travis. Can you look into what's up?

**Comment by patrickberkeley** [comment]
@lukemelia I've looked at this and am not sure what's causing the tests to fail. I tried upgrading ember and ember-cli (https://github.com/plyfe/ember-social/pull/17), but tests still fail there.

It's worth noting they're failing on master (https://travis-ci.org/plyfe/ember-social) and have been since https://github.com/plyfe/ember-social/pull/12 as far as I can tell.

**Pull request merged**
