### PR TITLE
Converts Services to Ember.Service extensions

### PR DESCRIPTION
**Pull request by danmcclain**
* Injects services via `Ember.inject` instead of initializer
* Removes Facebook facepile, Facebook deprecated/removed it
* Fixes tests

### CODE REVIEW

**Comment by danmcclain** [comment]
Tests intermittently failed locally

**Comment by kennethkalmer** [comment]
Just confirm, Facebook's Facepile stopped working [June 23rd, 2015](https://developers.facebook.com/docs/plugins/deprecated).

The failing tests on Travis should be because it is still building with Phantom 1.9. Rebasing this PR should probably fix it. I'll do a rebase this side as well to see.

**Comment by danmcclain** [comment]
@kennethkalmer What branch should this be rebased against? I'm not seeing anything with Phantom 2.0

**Comment by jschneier** [comment]
I'm seeing deprecations in Ember 1.13.x and this pull request has the fixes, is there anything I can do to get it over the line? The PR looks correct.

**Pull request closed without merging**
